WIP: Fix nix-on-droid build
21/05/26
After fixing ssh I did:
nix build "git+file:///home/nixos/.nix-config#nixosConfigurations.DANIELKNB1.config.system.build.toplevel" --impure --show-trace --builders ''
sudo ./result/activate
sudo ./result/bin/switch-to-configuration switch

Then I was able to:
sudo nix build .#nixOnDroidConfigurations.sams.activationPackage -L --impure -v  --option substituters "https://nix-on-droid.cachix.org" --option trusted-public-keys "nix-on-droid.cachix.org-1:56snoMJTXmDRC1Ei24CmKoUqvHJ9XCp+nidK7qkMQrU=" --show-trace --max-jobs 0

20/05/26
Threw
>error: path '/nix/store/3mbxpr3aybqb1vd12pymnmf9vwqhy302-proot-termux-static-aarch64-unknown-linux-android-0-unstable-2026-02-21' does not exist and cannot be created

See https://github.com/nix-community/nix-on-droid/issues/94#issuecomment-2380612109 ("Reason for the cache") for a workaround, maybe this can be a command line parameter ?
Used command line:
>nix build -L --impure --show-trace -vv "git+file:///home/nixos/.nix-config#nixOnDroidConfigurations.sams.activationPackage"