WIP: Fix nix-on-droid build
22/05/26
update: bat seemed to have caused, disabled bat on n-o-d
    nix-tree --impure --derivation  .#nixOnDroidConfigurations.sams.activationPackage
if depend. is listed here then
    nix path-info --recursive --closure-size --impure .#nixOnDroidConfigurations.sams.activationPackage | sort -nk2
after removing a non-buildable trans. depend. (*-python3.13* was introduced via shell aliases lol) there was
still /nix/store/434dh4zfr05gnsbq8f5jxg2ldi8clf3s-python3.13-mdit-py-plugins-0.4.2
listed in above path-info's output, but after why-depends it seemed to vanish, former seems not only to
evaluate when started like that but also to build the closure
    nix why-depends --impure .#nixOnDroidConfigurations.sams.activationPackage /nix/store/434dh4zfr05gnsbq8f5jxg2ldi8clf3s-python3.13-mdit-py-plugins-0.4.2
build was then unlocked
    nix build .#nixOnDroidConfigurations.sams.activationPackage -L --impure -v  --option substituters "https://nix-on-droid.cachix.org" --option trusted-public-keys "nix-on-droid.cachix.org-1:56snoMJTXmDRC1Ei24CmKoUqvHJ9XCp+nidK7qkMQrU=" --show-trace --max-jobs 0

sources:
- https://discourse.nixos.org/t/better-why-depends-fill-in-the-gaps/31246
- raw store paths https://discourse.nixos.org/t/nix-copy-closure-copies-things-that-nix-why-depends-cannot-explain/44544/2
- flake inputs other than nixpkgs https://discourse.nixos.org/t/nix-why-depends-on-a-non-standard-input/49872/6
- https://nix.dev/manual/nix/2.22/command-ref/new-cli/nix3-path-info#examples
- full closure https://discourse.nixos.org/t/nixos-rebuild-is-compiling-a-non-existent-package/75784/6

21/05/26
After fixing ssh I did:
    nix build "git+file:///home/nixos/.nix-config#nixosConfigurations.DANIELKNB1.config.system.build.toplevel" --impure --show-trace --builders ''
    sudo ./result/activate
    sudo ./result/bin/switch-to-configuration switch

Then I was able to:
    sudo nix build .#nixOnDroidConfigurations.sams.activationPackage -L --impure -v  --option substituters "https://nix-on-droid.cachix.org" --option trusted-public-keys "nix-on-droid.cachix.org-1:56snoMJTXmDRC1Ei24CmKoUqvHJ9XCp+nidK7qkMQrU=" --show-trace --max-jobs 0

20/05/26
Threw
>error: path '/nix/store/3mbxpr3aybqb1vd12pymnmf9vwqhy302-proot-termux-static-aarch64-unknown-linux-android-0-unstable-2026-02-21' does not exist and cannot be created

See https://github.com/nix-community/nix-on-droid/issues/94#issuecomment-2380612109 ("Reason for the cache") for a workaround, maybe this can be a command line parameter ?
Used command line:
>nix build -L --impure --show-trace -vv "git+file:///home/nixos/.nix-config#nixOnDroidConfigurations.sams.activationPackage"